server:
  port: 8100

spring:
  cloud:
    config:
      enabled: false
  application:
    name: currency-conversion-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

#currency-exchange-service:
#  first-service: http://localhost:8000
#  second-service: http://localhost:8001
#  urls:
#    - http://localhost:8002
#    - http://localhost:8001

##spring.cloud.config.enabled=true
#spring.application.name=currency-conversion-service
#server.port=8100
#currency-exchange-service.ribbon.listOfServers=http://localhost:8000, http://localhost:8001
#currency-exchange-service.first-service=http://localhost:8000
#currency-exchange-service.second-service=http://localhost:8001
